import type { Metadata } from "next";

import "../styles/globals.css";

import { appSpec } from "@/lib/spec";

export const metadata: Metadata = {
  title: `${appSpec.name} Dashboard`,
  description: "Generated by AI AppGen",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
