# {{APP_NAME}}

This project was generated by AI AppGen. It scaffolds a full-stack Next.js application with Supabase auth and CRUD flows derived from your prompt.

## Getting Started

1. Install dependencies:
   ```bash
   pnpm install
   ```
2. Copy `.env.example` to `.env.local` and populate Supabase credentials.
3. Run the database migration (requires the Supabase CLI):
   ```bash
   pnpm db:migrate
   ```
4. Start the dev server:
   ```bash
   pnpm dev
   ```

## Available Scripts

- `pnpm dev` – start Next.js in development mode.
- `pnpm build` / `pnpm start` – production build & start.
- `pnpm lint` – ESLint (flat config) with Next rules.
- `pnpm test` – Vitest suite covering spec validation and components.
- `pnpm db:migrate` – apply Supabase SQL migrations.

## Supabase Policies

The generated SQL migration enables row level security and restricts CRUD to the authenticated user via the `user_id` column. Adjust policies as needed.

## Environment Variables

Required keys exported in `.env.example`:

- `AI_PROVIDER` (`local` or `openai`)
- `OPENAI_API_KEY` and `OPENAI_MODEL`
- `NEXT_PUBLIC_SUPABASE_URL`
- `NEXT_PUBLIC_SUPABASE_ANON_KEY`
- Optional: `SUPABASE_SERVICE_ROLE_KEY` for migrations in CI/CD

## Deployment

Use any Next.js compatible platform (Vercel, Supabase, etc.). Ensure required environment variables are configured and Supabase migrations are applied in production.
